export const phoneFormats = {
  US: '(XXX) XXX-XXXX',
  CA: '(XXX) XXX-XXXX',
  BS: '(XXX) XXX-XXXX',
  MX: 'XX XXXX-XXXX',
  IN: 'XXXXX-XXXXX',
  ID: 'XX-XXXX-XXXX',
  PK: 'XXX-XXXXXXX',
  BR: 'XX XXXXX-XXXX',
  NG: 'XXX XXX XXXX',
  BD: 'XXXX-XXXXXX',
  RU: 'XXX XXX-XX-XX',
  JP: 'XX-XXXX-XXXX',
  PH: 'XX-XXXX-XXXX',
  GB: 'XX XXXX XXXX',
  VN: 'XX-XXXX-XXXX',
  ET: 'XX XXX XXXX',
  EG: 'XX XXXX XXXX',
  DE: 'XXXX XXXXXXX',
  IR: 'XXX-XXX-XXXX',
  TR: 'XXX XXX XXXX',
  CD: 'XXX XXX XXX',
  FR: 'X XX XX XX XX',
  AR: 'XX XXXX-XXXX',
  CL: 'XX XXXX XXXX',
  CO: 'XXX XXX XXXX',
  VE: 'XXX XXX XXXX',
  BO: 'XX XXX XXXX',
  PY: 'XXX XXX XXX',
  UY: 'XXX XXX XXX',
  EC: 'XX XXX XXXX',
  GY: 'XXX XXXX',
  SR: 'XXX-XXXX',
  PE: 'XXXXXXXXXX',
  CR: 'XXXX XXXX',
  PA: 'XXX-XXXX',
  JM: 'XXX-XXX-XXXX',
  TT: 'XXX-XXXX',
  DO: 'XXX-XXX-XXXX',
  CU: 'XXX-XXXX',
  GT: 'XXXX XXXX',
  HN: 'XXXX-XXXX',
  SV: 'XXXX-XXXX',
  NI: 'XXXX-XXXX',
  PR: '(XXX) XXX-XXXX',
  UK: 'XXXXX XXXXXX',
  ES: 'XXX XX XX XX',
  IT: 'XXX XXXXXXX',
  NL: 'XX XXX XXXX',
  BE: 'XXX XX XX XX',
  CH: 'XX XXX XX XX',
  AT: 'XXXX XXXXXXX',
  SE: 'XX-XXX XX XX',
  NO: 'XXX XX XXX',
  DK: 'XX XX XX XX',
  FI: 'XX XXX XXXX',
  IE: 'XX XXXX XXXX',
  PT: 'XXX XXX XXX',
  UA: 'XX XXX XX XX',
  PL: 'XXX XXX XXX',
  CZ: 'XXX XXX XXX',
  SK: 'XXX XXX XXX',
  HU: 'XX XXX XXXX',
  RO: 'XXX XXX XXX',
  BG: 'XXX XXX XXX',
  RS: 'XX XXX XXXX',
  HR: 'XX XXX XXXX',
  BA: 'XX XXX XXXX',
  SI: 'XX XXX XXX',
  MK: 'XX XXX XXXX',
  AL: 'XX XXX XXXX',
  MT: 'XX XX XX XX',
  CY: 'XX XXX XXXX',
  GR: 'XX XXX XXXX',
  CN: 'XX-XXXX-XXXX',
  KR: 'XX-XXXX-XXXX',
  TH: 'XX XXX XXXX',
  MY: 'XX-XXX XXXX',
  SG: 'XXXX XXXX',
  HK: 'XXXX XXXX',
  TW: 'XX XXXX XXXX',
  LK: 'XX XXX XXXX',
  NP: 'XX-XXXXXXX',
  MM: 'XX-XXXXXXX',
  KH: 'XX-XXX-XXX',
  LA: 'XX-XXX-XXX',
  MN: 'XX-XX-XXXX',
  KZ: 'XXX XXX XXXX',
  UZ: 'XX-XXX-XX-XX',
  KG: 'XXX-XX-XX-XX',
  TJ: 'XXX-XX-XX-XX',
  TM: 'XXX-XX-XX-XX',
  AE: 'XX XXX XXXX',
  SA: 'XX XXX XXXX',
  IQ: 'XXX XXX XXXX',
  SY: 'XX-XXXX-XXXX',
  JO: 'XX XXXX XXXX',
  LB: 'XX XXX XXX',
  IL: 'XX-XXX-XXXX',
  OM: 'XX XXX XXXX',
  YE: 'XXX XXX XXX',
  QA: 'XX XXX XXXX',
  KW: 'XXX XXXX',
  BH: 'XXXX XXXX',
  ZA: 'XX XXX XXXX',
  TZ: 'XX XXX XXXX',
  KE: 'XXX XXX XXX',
  UG: 'XXX XXX XXX',
  SD: 'XX XXX XXXX',
  GH: 'XXX XXX XXXX',
  CM: 'XXXX XXXX',
  CI: 'XX XX XX XX',
  MG: 'XX XX XXX XX',
  AO: 'XX XXX XXXX',
  MZ: 'XX XXX XXXX',
  ZM: 'XXX XXX XXX',
  ZW: 'XX XXX XXXX',
  SN: 'XX XXX XXXX',
  ML: 'XX XX XX XX',
  TG: 'XX XX XX XX',
  NE: 'XX XX XX XX',
  BF: 'XX XX XX XX',
  BJ: 'XX XX XX XX',
  SL: 'XX XXX XXX',
  LR: 'XX XXX XXX',
  MW: 'XX XXX XXX',
  RW: 'XX XXX XXX',
  BI: 'XX XXX XXX',
  CG: 'XX XXX XXXX',
  GA: 'XX XX XX XX',
  GQ: 'XX XXX XXXX',
  ST: 'XX XXX XXX',
  NA: 'XX XXX XXXX',
  BW: 'XX XXX XXXX',
  SZ: 'XX XXX XXXX',
  LS: 'XX XXX XXXX',
  ER: 'X XXX XXXX',
  DJ: 'XX XX XX XX',
  SO: 'XX XXX XXXX',
  GM: 'XXX XX XX',
  CV: 'XXX XX XX',
  GW: 'XX XXX XXX',
  IS: 'XXX XXXX',
  FJ: 'XX XXXXX',
  PG: 'XXX-XXXXX',
  TO: 'XX-XXXXX',
  WS: 'XX-XXXXX',
  SB: 'XXX-XXXXX',
  MH: 'XXX-XXXX',
  FM: 'XXX-XXXX',
  PW: 'XXX-XXXX',
  KI: 'XXX-XXXX',
  NR: 'XXX-XXXX',
  TV: 'XXX-XXXX',
  AU: 'XX XXXX XXXX',
  NZ: 'XX XXX XXXX'
};

export function formatPhone(value: string, format: string) {
  const cleaned = ('' + value).replace(/\D/g, '');
  let formatted = '';
  let j = 0;

  console.log(formatted);
  for (let i = 0; i < format.length && j < cleaned.length; i++) {
    if (format[i] === 'X') {
      formatted += cleaned[j];
      j++;
    } else {
      formatted += format[i];
    }
  }
  console.log(formatted);

  return formatted;
}
